In [1]:
import numpy as np
import pandas as pd

In [3]:
data = {
'Date': pd.date_range( '2023-01-01', periods=20),
'Product': ['A', 'B', 'C', 'D'] * 5,
'Region': ['East', 'West', 'North', 'South', 'East', 'West', 'North', 'South', 'East', 'West',
'North', 'South', 'East', 'West', 'North', 'South', 'East', 'West', 'North', 'South'],
'Sales': np.random. randint(100, 1000, 20),
'Units': np.random.randint(10, 100, 20),
'Rep': ['John', 'Mary', 'Bob', 'Alice', 'John', 'Mary', 'Bob', 'Alice', 'John', 'Mary',
        'Bob', 'Alice', 'John', 'Mary', 'Bob', 'Alice', 'John', 'Mary', 'Bob', 'Alice']
}
df = pd.DataFrame(data)

df['Month'] = df['Date'].dt.month_name()
df['Quarter'] = 'Q' + df['Date'].dt.quarter.astype(str)
df

         Date Product Region  Sales  Units    Rep    Month Quarter
0  2023-01-01       A   East    648     30   John  January      Q1
1  2023-01-02       B   West    565     61   Mary  January      Q1
2  2023-01-03       C  North    668     80    Bob  January      Q1
3  2023-01-04       D  South    356     89  Alice  January      Q1
4  2023-01-05       A   East    881     77   John  January      Q1
5  2023-01-06       B   West    321     64   Mary  January      Q1
6  2023-01-07       C  North    272     58    Bob  January      Q1
7  2023-01-08       D  South    190     35  Alice  January      Q1
8  2023-01-09       A   East    743     97   John  January      Q1
9  2023-01-10       B   West    132     51   Mary  January      Q1
10 2023-01-11       C  North    627     91    Bob  January      Q1
11 2023-01-12       D  South    712     96  Alice  January      Q1
12 2023-01-13       A   East    699     38   John  January      Q1
13 2023-01-14       B   West    850     42   Mary  January      Q1
14 2023-01-15       C  North    174     37    Bob  January      Q1
15 2023-01-16       D  South    737     64  Alice  January      Q1
16 2023-01-17       A   East    106     50   John  January      Q1
17 2023-01-18       B   West    220     15   Mary  January      Q1
18 2023-01-19       C  North    904     84    Bob  January      Q1
19 2023-01-20       D  South    995     21  Alice  January      Q1

In [6]:
pd.pivot_table(df,values='Sales',index='Region',columns='Product',aggfunc='median')

Product      A      B      C      D
Region
East     699.0    NaN    NaN    NaN
North      NaN    NaN  627.0    NaN
South      NaN    NaN    NaN  712.0
West       NaN  321.0    NaN    NaN

In [8]:
pivot2=pd.pivot_table(df,values=['Sales','Units'],index='Region',columns='Product')
pivot2

         Sales                      Units
Product      A      B      C      D     A     B     C     D
Region
East     615.4    NaN    NaN    NaN  58.4   NaN   NaN   NaN
North      NaN    NaN  529.0    NaN   NaN   NaN  70.0   NaN
South      NaN    NaN    NaN  598.0   NaN   NaN   NaN  61.0
West       NaN  417.6    NaN    NaN   NaN  46.6   NaN   NaN

#### Cross Tabs

In [ ]:
pd.crosstab(df['Region'],df['Product']) 
# CrossTab is used for counting Purpose

Product  A  B  C  D
Region
East     5  0  0  0
North    0  0  5  0
South    0  0  0  5
West     0  5  0  0